### ISSUE TITLE
something wrong?

### ISSUE THREAD

**Issue by yanyq1990** [uber-research/DeepPruner#1]
Is there something wrong in line 183, 256, 265 of file DeepPruner/deeppruner/models/patch_match.py

1. line 183: modify if **type** is "horizontal": to if **propagation_type** is "horizontal":
2. line 256: modify normalized_disparity_samples = self.propagation(normalized_disparity_samples, device, **1**) to normalized_disparity_samples = self.propagation(normalized_disparity_samples, device, '**horizontal**')
3. line 265: modify normalized_disparity_samples = self.propagation(normalized_disparity_samples, device, **0**) to normalized_disparity_samples = self.propagation(normalized_disparity_samples, device, '**vertical**')

**Comment by ShivamDuggal4** [comment]
Hi @yanyq1990 Thanks for pointing this out. 
This typo happened during code cleaning. I have fixed this.
