### ISSUE TITLE
about submission_kitti.py

### ISSUE THREAD

**Issue by YongYongLi123** [uber-research/DeepPruner#11]
Hello:
When I run submission_kitti.py I get RuntimeError: cuda runtime error (11): invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663, what should I do, thanks

**Comment by ShivamDuggal4** [comment]
Hi @YongYongLi123 
This is probably some issue with your CUDA setup. Check this [link](https://discuss.pytorch.org/t/cuda-runtime-error-11/30080).

You can set `args.cuda` parameter as False, in case you do not want to use it.

Closing this issue on this note, feel free to reopen in case of any further issue.
