### ISSUE TITLE
Question about the Random Part

### ISSUE THREAD

**Issue by yanqswhu** [uber-research/DeepPruner#12]
Hi, thanks for your sharing and work. I watched your paper&code and some questions really confuse me. I will appreciate if you could answer these questions.

I tried to only use the Differential-PatchMatch of your network to predict the depth, but I didn't get any useful disparity information. It seemed that the random part disturbed the training process. 
How do you think of the random part of the network?  Does it really works under the forward-backward method?

Thanks.

**Comment by shenlongwang** [comment]
Hi @Yannnnnnnnnnnn only using patchmatch layer itself by taking raw RGB color as input would not provide robust disparity estimation. This is same for conventional patchmatch, as these nearest neighbor field method relies on robust feature representation. Please refer to deeppruner folder to see how to build a reliable and efficient stereo estimation network.
