### ISSUE TITLE
about the batchsize

### ISSUE THREAD

**Issue by xubin1994** [uber-research/DeepPruner#13]
Hello, I want to reproduce your model, but I found that the quality is not as good as the model you provided. In your paper, you used batchsize = 16, but you used batchsize = 1 in your code. so which is the batchsize used by your model?
I use the model you provided to predict my test set. The overall performance is very good and complete. the disp is as follow:
![image](https://user-images.githubusercontent.com/28856641/76413312-27c83100-63d0-11ea-8240-90b5facc798f.png)

However, if I use the model I trained to predict, I will lose some details (such as fingers). the disp is as follow:
![image](https://user-images.githubusercontent.com/28856641/76413412-56460c00-63d0-11ea-8a39-f0b07143a830.png)

What do you think may caused this difference?

**Comment by ShivamDuggal4** [comment]
HI @xubin1994  Glad that you liked our work. The batch size we used is 16, as we mentioned in the paper. 
Your result looks very good too. TBH, it's very hard to tell what could have caused such a minute difference. The results can always change slightly with re-training, with the GPU you used for training, with your environment (dependencies versions) etc.

Thanks, feel free to reopen if there is any other doubt.
