### ISSUE TITLE
about the normalized_disparity_samples

### ISSUE THREAD

**Issue by xubin1994** [uber-research/DeepPruner#14]
Hello, I read your code, there is a bit of confusion about normalized_disparity_samples in patch_match.py, why would you use two variables: disparity_samples and normalized_disparity_samples to do the PatchMatch?
 It feels just to use disparity_samples for propagation and evaluation, and it can achieve the same goal and saves calculations.

**Comment by ShivamDuggal4** [comment]
Hi @xubin1994 

PatchMatch has 3 operations: Sampling, Propagation and Evaluation.
As mentioned in the paper and in implementation, we divide the entire disparity search range into k bins, sample 1 disparity particle from each bin and then perform propagation/ evaluation on each bin separately, forcing the i-th particle to be in a i−th interval.

As shown in Figure 1. of the paper, we apply PatchMatch 2 times, one on the original disparity search range and later on the reduced search range.

- During the first instance of PatchMatch, the search range of each pixel would be same (say, 0- max_disparity/4), therefore after PatchMatch operations, the i-th sampled disparity particle would be in the i-th bin, for sure.

- However, during the second instance, there is no guarantee that the disparity search range of neighbouring pixels would be similar. Thus to make sure, that the i-th sampled disparity particle stays in the i-th bin after PatchMatch operations, we need to perform PatchMatch on the normalized disparity space.

Thus, to keep the code generic enough to be applied in cases where neighbouring pixels have different search ranges, we used the two variables: disparity_samples and normalized_disparity_samples

We perform PatchMatch propagation on the normalized disparity space, and then transform the normalized particles to the original space as in lines: 

https://github.com/uber-research/DeepPruner/blob/7cfd5e6845397683a98ea5a878f05e221c5dee79/deeppruner/models/patch_match.py#L256

Hope this helps. 
Regards.
