### ISSUE TITLE
Questions about PatchMatch

### ISSUE THREAD

**Issue by EmilyLike** [uber-research/DeepPruner#21]
Hello, I am trying to find some quickly code about patchmatch,  then I have read your code about Differentiable patchmatch.  the key about first step is to extractor features by conv3d.  So I wonder if I wanna know is this differentiable patchmatch is just fit to Stereo Matching or it can be treated as a torch implemention version of patchmatch?

**Comment by ShivamDuggal4** [comment]
Hi @EmilyLike

**Comment by shenlongwang** [comment]
Thanks for your interest @EmilyLike . Yeah we did have a demo on a differentiable version of patchmatch, conducting image reconstruction. Please see the link here: https://github.com/uber-research/DeepPruner/tree/master/DifferentiablePatchMatch
