### ISSUE TITLE
skimage.io.imsave Error regarding .join()

### ISSUE THREAD

**Issue by bricksaver** [uber-research/DeepPruner#22]
_Hi, I am running into an error on the 2nd to final line of the submission_kitti.py file, namely, the following line:_

**"skimage.io.imsave(os.path.join(args.save_dir, image_L_path.split(('/')[-1]), (disparity_comb * 256).astype('uint16')))"**

_The error I am getting is:_

Traceback (most recent call last):
  File "submission_kitti.py", line 173, in <module>
    main()
  File "submission_kitti.py", line 160, in main
    skimage.io.imsave(os.path.join(args.save_dir, (disparity * 256).astype('uint16')))
  File "/home/benjamin/anaconda3/lib/python3.6/posixpath.py", line 92, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/benjamin/anaconda3/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'ndarray'

_Do you have any idea why this might be?_
_When I print out args.save_dir, I get_ **./** _and when I print out_ **image_L_path.split(('/')[-1]), (disparity_comb * 256).astype('uint16'))**, I get **['.', 'unity_chair', 'rgb_chair_left', '0002.jpg'] []**

_My code is below as follows:_

`from __future__ import print_function
import argparse
import os
import random
import torch
import torch.nn as nn
import torch.nn.parallel
import torch.backends.cudnn as cudnn
import torch.optim as optim
import torch.utils.data
from torch.autograd import Variable
import torch.nn.functional as F
import skimage.io
import numpy as np
import logging
from dataloader import kitti_submission_collector as ls
from dataloader import preprocess
from PIL import Image
from models.deeppruner import DeepPruner
from models.config import config as config_args
from setup_logging import setup_logging
import cv2

parser = argparse.ArgumentParser(description='DeepPruner')
parser.add_argument('--datapath', default='/',
                    help='datapath')
parser.add_argument('--loadmodel', default=None,
                    help='load model')
parser.add_argument('--save_dir', default='./',
                    help='save directory')
parser.add_argument('--logging_filename', default='./submission_kitti.log',
                    help='filename for logs')
parser.add_argument('--no-cuda', action='store_true', default=False,
                    help='enables CUDA training')
parser.add_argument('--seed', type=int, default=1, metavar='S',
                    help='random seed (default: 1)')

args = parser.parse_args()
torch.backends.cudnn.benchmark = True
args.cuda = not args.no_cuda and torch.cuda.is_available()

args.cost_aggregator_scale = config_args.cost_aggregator_scale
args.downsample_scale = args.cost_aggregator_scale * 8.0

setup_logging(args.logging_filename)

if args.cuda:
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    random.seed(args.seed)
    torch.cuda.manual_seed(args.seed)
    torch.backends.cudnn.deterministic = True

#test_left_img, test_right_img = ls.datacollector(args.datapath)

model = DeepPruner()
model = nn.DataParallel(model)

if args.cuda:
    model.cuda()

logging.info('Number of model parameters: {}'.format(sum([p.data.nelement() for p in model.parameters()])))

if args.loadmodel is not None:
    logging.info("loading model...")
    state_dict = torch.load(args.loadmodel)
    model.load_state_dict(state_dict['state_dict'], strict=True)

def test(imgL, imgR):
    model.eval()
    with torch.no_grad():
        imgL = Variable(torch.FloatTensor(imgL))
        imgR = Variable(torch.FloatTensor(imgR))

        if args.cuda:
            imgL, imgR = imgL.cuda(), imgR.cuda()

        refined_disparity = model(imgL, imgR)
        return refined_disparity

def main():

    name_save_idx = 0
    #for left_image_path, right_image_path in zip(test_left_img, test_right_img):
    for i in range(2,3):
        name_save_idx += 1
        left_img_path = './unity_chair/rgb_chair_left/'
        right_img_path = './unity_chair/rgb_chair_right/'
        image_L_path = './unity_chair/rgb_chair_left/' + '{:04d}'.format(i) + '.jpg' #CHECK TO CHANGE B4 RUNNING
        print('i:', i)
        image_R_path = './unity_chair/rgb_chair_right/' + '{:04d}'.format(i) + '.jpg' #CHECK TO CHANGE B4 RUNNING
        #imgL = cv2.imread(image_L_path,0)
        #imgR = cv2.imread(image_R_path,0)
        #imgL = cv2.imread(image_L_path)
        #imgR = cv2.imread(image_R_path)

        imgL = np.asarray(Image.open(image_L_path))
        imgR = np.asarray(Image.open(image_R_path))
        print('imgL 0',imgL)
        print('imgR 0',imgR)
        print('POINT 0')
        #print('IMGL SHAPE:',imgL.shape)
        #iprint('IMGR SHAPE:',imgR.shape)
        processed = preprocess.get_transform()
        print('POINT 1')
        imgL = processed(imgL).numpy()
        imgR = processed(imgR).numpy()
        print('IMG 1',imgL)
        print('IMGR 1',imgR)
        imgL = np.reshape(imgL, [1, 3, imgL.shape[1], imgL.shape[2]])
        imgR = np.reshape(imgR, [1, 3, imgR.shape[1], imgR.shape[2]])
        print('IMGL 2',imgL)
        print('IMGR 2',imgR)

        w = imgL.shape[3]
        h = imgL.shape[2]
        dw = int(args.downsample_scale - (w%args.downsample_scale + (w%args.downsample_scale==0)*args.downsample_scale))
        dh = int(args.downsample_scale - (h%args.downsample_scale + (h%args.downsample_scale==0)*args.downsample_scale))

        top_pad = dh
        left_pad = dw
        imgL = np.lib.pad(imgL, ((0, 0), (0, 0), (top_pad, 0), (0, left_pad)), mode='constant', constant_values=0)
        imgR = np.lib.pad(imgR, ((0, 0), (0, 0), (top_pad, 0), (0, left_pad)), mode='constant', constant_values=0)

        disparity = test(imgL, imgR)
        print('POINT 0')
        print('DISPARITY:',disparity)
        print('DISPARITY TYPE:',type(disparity))
        #print('DISPARITY SHAPE:',disparity.shape)
        #disparity = list(disparity)
        #disparity = np.array(disparity)
        #print(disparity)
        print('TOP PAD:',top_pad)
        print('LEFT_PAD:',left_pad)
        disparity = disparity[0, top_pad:, :-left_pad].data.cpu().numpy()  
        print('POINT 1')
        print('NEED TO FIX ISSUE BELOW')

        skimage.io.imsave(os.path.join(args.save_dir, image_L_path.split(('/')[-1]), (disparity_comb * 256).astype('uint16')))
        print('POINT 3')
        #skimage.io.imsave(os.path.join(args.save_dir, (disparity * 256).astype('uint16')))
        filename = 'unity_chair_estimated_disparity_pair_dp_' + '{:04d}'.format(name_save_idx) + '.png'
        #disparity = np.uint16(disparity)
        print('POINT 4')
        #img = Image.fromarray(disparity_comb, 'RGB')
        #img.save(filename)
        ('POINT 5')
        #cv2.imwrite(filename,disparity_comb)

        logging.info("Disparity for {} generated at: {}".format(left_image_path, os.path.join(args.save_dir, left_image_path.split('/')[-1])))

if __name__ == '__main__':
        main()`

**Comment by ShivamDuggal4** [comment]
Hi @bricksaver  it looks me to that your config is not set correctly for evaluation. Changing the `mode`  to `evaluation` should solve this issue.
https://github.com/uber-research/DeepPruner/blob/40b188cf954577e21d5068db2be2bedc6b0e8781/deeppruner/models/config.py#L31

**Comment by bricksaver** [comment]
Hi @ShivamDuggal4 Thank you for the reply! I really appreciate it. I did have my mode set to "evaluation" in my config.py file already (as I saw from a previous issue that had been posted). It helped me run the following line: 

disparity = disparity[0, top_pad:, :-left_pad].data.cpu().numpy()   

However, my code became stuck on the line after after. Do you know what else might be causing the above mentioned error to appear?

**Comment by ShivamDuggal4** [comment]
Hi @bricksaver , it seems there is  a small error in your code.

Below is the traceback you posted above. It shows a bug in your line 160, `skimage.io.imsave(os.path.join(args.save_dir, (disparity * 256).astype('uint16')))`. But your code has this line commented actually.  So either the traceback is outdated or the code. Please check this.

It seems there is no error in the DeepPruner part, there is just a syntax error in your code while saving the disparity image.

```
Traceback (most recent call last):
File "submission_kitti.py", line 173, in
main()
File "submission_kitti.py", line 160, in main
skimage.io.imsave(os.path.join(args.save_dir, (disparity * 256).astype('uint16')))
File "/home/benjamin/anaconda3/lib/python3.6/posixpath.py", line 92, in join
genericpath._check_arg_types('join', a, *p)
File "/home/benjamin/anaconda3/lib/python3.6/genericpath.py", line 149, in _check_arg_types
(funcname, s.class.name)) from None
TypeError: join() argument must be str or bytes, not 'ndarray'
```

**Comment by bricksaver** [comment]
Hi, I ended up getting it it to work by using "cv2.imwrite(filename,disparity[0])" instead to save my output file. Thanks for the help!
