### ISSUE TITLE
Model Evaluation

### ISSUE THREAD

**Issue by bricksaver** [uber-research/DeepPruner#23]
Hi @ShivamDuggal4 

I am trying to load a pretrained model to do evaluation with the code. The commandline I am using is as follows: 

`python submission_kitti.py  --loadmodel ./dataloader/sceneflow_loader.py --save_dir ./ --datapath ./test_directory`

However, I am getting the following error:

`Traceback (most recent call last):
  File "submission_kitti.py", line 84, in <module>
    state_dict = torch.load(args.loadmodel)
  File "/home/benjamin/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/benjamin/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '#'.`

Is sceneflow_loader.py the right file to try to load? I also tried sceneflow_collector.py and a couple others in the dataloader folder, but they all gave the same error.

Do I need to download the pretrained model from somewhere?

**Comment by ShivamDuggal4** [comment]
Hi @bricksaver  
None of those is the model file. These are the model files: https://github.com/uber-research/DeepPruner/tree/master/deeppruner#model-weights. 
To run on any dataset:

- Download any of the models. (Note: We provide trained models only for KITTI and sceneflow dataset)
-  Adjust the config file according to the type of model (DeepPruner-best vs DeepPruner-fast) you want to run.
-  Run the evaluation command as described here: https://github.com/uber-research/DeepPruner/tree/master/deeppruner#evaluation-command-on-any-dataset

**Comment by bricksaver** [comment]
Thank you! I got my code running now.
