### ISSUE TITLE
Model Weights

### ISSUE THREAD

**Issue by zhanghang1996** [uber-research/DeepPruner#24]
I can't decompress the DeepPruner-best-kitti.tar document etc.

**Comment by ShivamDuggal4** [comment]
Hi @zhanghang1996  you don't need to decompress torch model. Please check `torch.load` documentation on how to load a pytorch model.

Eg: You just need to set `args.loadmodel` to the download directory of the `DeepPruner-best-kitti.tar` to use it for evaluation.
https://github.com/uber-research/DeepPruner/blob/40b188cf954577e21d5068db2be2bedc6b0e8781/deeppruner/submission_kitti.py#L82

**Comment by zhanghang1996** [comment]
> Hi @zhanghang1996 you don't need to decompress torch model. Please check `torch.load` documentation on how to load a pytorch model.
> 
> Eg: You just need to set `args.loadmodel` to the download directory of the `DeepPruner-best-kitti.tar` to use it for evaluation.
> https://github.com/uber-research/DeepPruner/blob/40b188cf954577e21d5068db2be2bedc6b0e8781/deeppruner/submission_kitti.py#L82
Thank you very much!
