### ISSUE TITLE
Test image size problem

### ISSUE THREAD

**Issue by QingWindIsStillTheWind** [uber-research/DeepPruner#26]
I would like to ask the  author, if the size of the image used for network training is 960x540, then when I want to use this network test, the resolution of the photos taken by my camera is very large, such as 4608x3456. When I take this picture to test, the parallax map effect is very bad. When I resize the original image to 960x540, the parallax map effect is very good OK, but I don't know how to restore the parallax value of the original image. If the high-resolution image（4608x3456） is cut（960x540） and then put into the prediction, the prediction effect of each small resolution image cut out is not good.Or how to use your network to test higher resolution images without enough similar data sets to train? Hope that the author can guide, thank you very much!

**Comment by ShivamDuggal4** [comment]
HI @QingWindIsStillTheWind , when you change the resolution of the image, the intrinsics change and thus the disparity range.
When you trained with lower resolution images, you trained your network with a particular disparity range.
When you test high resolution images by first reducing their resolution, predicting the disparity map and then converting it back to the original resolution, it should work well as you mentioned.

**Comment by ShivamDuggal4** [comment]
HI @QingWindIsStillTheWind , when you change the resolution of the image, the intrinsics change and thus the disparity range.
When you trained with lower resolution images, you trained your network with a particular disparity range.
When you test with high resolution images by first reducing their resolution, predicting the disparity map and then converting it back to the original resolution, it should work well as you mentioned. Increase the disparity map by the same factor with which you increase the resolution. This could be a possible way.

When you test on a crop of the high resolution image w/o reducing the resolution, the network outputs wrong parallax, because it's not trained to predict high resolution disparity range.

Let me know if you have more questions.

**Comment by QingWindIsStillTheWind** [comment]
Thank you very much for your answers. I have a few questions here to ask you. First, according to the method you said, after reducing the resolution of the picture, and then put it into the network for testing, we tried this method. However, the method we used to reduce the image resolution is the resize () method in opencv, which restores the 3D world coordinates of the object after compensating parallax. After calculating this, there will be 7-9mm error. I wonder if you have any suggestions for improving the image resolution reduction? Secondly, I wanted to use deepprun to train high-resolution and large parallax images, but it is difficult to train because of the lack of such data sets. Can deepprunner be used to train high-resolution images? For example, a resolution of 4000x3000.

Looking forward to your advice, thank you!

**Comment by ShivamDuggal4** [comment]
Hi @QingWindIsStillTheWind  
For image downsampling, maybe you can try opencv's bicubic interpolation.

DeepPruner can definitely be used for learning high-resolution disparity maps. Infact, compared to other approaches, which form the full cost-volume (and would thereby go out of memory for higher-resolution images/ larger disparity range), DeepPruner reduces the disparity search space (and hence the memory requirement) signifiacntly, allowing you to train on higher-resolution images.

**Comment by QingWindIsStillTheWind** [comment]
At 2020-11-19 01:16:48, "Shivam Duggal" <notifications@github.com> wrote:

HI @QingWindIsStillTheWind , when you change the resolution of the image, the intrinsics change and thus the disparity range.
When you trained with lower resolution images, you trained your network with a particular disparity range.
When you test with high resolution images by first reducing their resolution, predicting the disparity map and then converting it back to the original resolution, it should work well as you mentioned. Increase the disparity map by the same factor with which you increase the resolution. This could be a possible way.

When you test on a crop of the high resolution image w/o reducing the resolution, the network outputs wrong parallax, because it's not trained to predict high resolution disparity range.

Let me know if you have more questions.
