### ISSUE TITLE
Default maximum disparity

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [uber-research/DeepPruner#27]
What is the default maximum disparity range used in this model?

I cannot find any such parameter in the code. When I ran PSMNet, there was a parameter max_disp to set the maximum disparity value. I am looking for one such parameter in deeppruner.

**Comment by ShivamDuggal4** [comment]
Hi @Diksha-Moolchandani  the default max-disparity is set in `models/config.py` file: https://github.com/uber-research/DeepPruner/blob/40b188cf954577e21d5068db2be2bedc6b0e8781/deeppruner/models/config.py#L29

And its used in `models/deeppruner.py` file: https://github.com/uber-research/DeepPruner/blob/40b188cf954577e21d5068db2be2bedc6b0e8781/deeppruner/models/deeppruner.py#L31

**Comment by Diksha-Moolchandani** [comment]
thanks a lot
