### ISSUE TITLE
Parameters: input size, output size, in/out channels, stride and padding for all the layers

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [uber-research/DeepPruner#28]
Hi,

I need all the parameters for the layers in deeppruner. I tried extracting this information from the text and figure 1 but some information is missing and hence I am not able to figure out the parameters. 
Can you please share this information with me?

regards,
Diksha

**Comment by ShivamDuggal4** [comment]
Hi @Diksha-Moolchandani 

You can refer to our supplementary tables 2,3,4 for this information.
Supplementary: https://shivamduggal4.github.io/project_pages/deeppruner/supplementary.pdf

And you can also check through the model files in the directory:  https://github.com/uber-research/DeepPruner/tree/master/deeppruner/models

**Comment by Diksha-Moolchandani** [comment]
Thanks
