### ISSUE TITLE
no-cuda error

### ISSUE THREAD

**Issue by oxm** [uber-research/DeepPruner#3]
@ShivamDuggal4 
args.cuda = True,submission_kitti.py runs correctly,when I set --no-cuda,args.cuda=False,such error appeared:
 
Traceback (most recent call last):
  File "submission_kitti.py", line 83, in <module>
    model.load_state_dict(state_dict['state_dict'], strict=True)
  File "/home/xxm/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DeepPruner:

**Comment by ShivamDuggal4** [comment]
Hi @oxm , Just take `model = nn.DataParallel(model)` out of the `if args.cuda:` block in the line https://github.com/uber-research/DeepPruner/blob/2b5a0e92735333376df16a46e91b6b215b08c797/deeppruner/submission_kitti.py#L73

I will edit it in some of the later commits.

**Comment by oxm** [comment]
@ShivamDuggal4 hi,according to your opinion, the problem was sovled.
