### ISSUE TITLE
tuple indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by bucky999** [uber-research/DeepPruner#32]
When I run python submission_kitti.py, I get an error:
  File "DeepPruner/deeppruner/submission_kitti.py", line 123, in main
    disparity = disparity[top_pad:, :-left_pad].data.cpu().numpy()
TypeError: tuple indices must be integers or slices, not tuple

**Comment by ShivamDuggal4** [comment]
Hi @bucky999, 
It seems like your config file hasn't been set correctly for evaluation.
https://github.com/uber-research/DeepPruner/blob/b13a254773843b92ee8bbfb5dbc18cf9a3078ea4/deeppruner/models/config.py#L31

Please change the `"mode"` to `"evaluation"` to successfully run `submission_kitti.py`. Most probably, this should do the fix.
