### ISSUE TITLE
Cannot unpack pre-trained models from provided links.

### ISSUE THREAD

**Issue by wiktorpi** [uber-research/DeepPruner#33]
Hello!
I tried downloading your pre-trained models from the links provided but it seems that the tarballs are broken and do not unpack.
```
tar -xvf DeepPruner-fast-kitti.tar 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```
This issue is the same for all 4 models.
I have re-downloaded and verified on different systems and the problem persists.
I would like to try your models and would be grateful for help

**Comment by ShivamDuggal4** [comment]
Hi @wiktorpi 

You do not need to unpack the pre-trained torch models.  Simply pass them to torch.load as in:
https://github.com/uber-research/DeepPruner/blob/40b188cf954577e21d5068db2be2bedc6b0e8781/deeppruner/submission_kitti.py#L82

You can also check the pytorch documentation [here](https://pytorch.org/docs/stable/generated/torch.load.html#torch.loadstate_dict%20=%20torch.load(args.loadmodel) ).
