### ISSUE TITLE
The source file is corrupt

### ISSUE THREAD

**Issue by luffy-66** [uber-research/DeepPruner#42]
hello，the model weights list is corrupt，please check and update，ths！

Model Weights
DeepPruner was first trained on Sceneflow dataset and then finetuned on KITTI (Combined 394 images of KITTI-2012 and KITTI-2015) dataset.

[DeepPruner-fast (KITTI)](https://drive.google.com/open?id=1jJAawAUcTpmhj8YdG7BWonglKpfQ8oMN)
[DeepPruner-best (KITTI)](https://drive.google.com/open?id=1mSendpKq0vdQMr5XVp5zAHm37dwEgcun)
[DeepPruner-fast (Sceneflow)](https://drive.google.com/open?id=1n5lhhFDb07s6NtlLG8_pnnfwI7bLnSVx)
[DeepPruner-best (Sceneflow)](https://drive.google.com/open?id=1y6V9A4B4LlrkIMflgcykNgD0oQwUf7AC)

**Comment by ShivamDuggal4** [comment]
Hi @luffy-66 

I am able to download and access all the weights. Can you please provide the exact error message you are getting while downloading the weights ?

Best Regards
Shivam

**Comment by leizhenyu-lzy** [comment]
> 

so there's no need to extract or unzip it?
