### ISSUE TITLE
Experiment on pytorch2.0.0

### ISSUE THREAD

**Issue by leizhenyu-lzy** [uber-research/DeepPruner#43]
in torch                     2.0.0

```python
disparity = torch.cat(disparity, dim=0)
```

need to be added to the submission_kitti.py after

```python
disparity = test(imgL, imgR)
```

**Comment by ShivamDuggal4** [comment]
Hi @leizhenyu-lzy 

Thanks for sharing this update. Hopefully, if anyone faces this problem, this issue will help them fix it faster.
I don't have the datasets and the pytorch environment on my current machine to test, so I will leave it as an issue. But I appreciate you sharing this.

Best Regards,
Shivam
