### ISSUE TITLE
finetune_kitti.py does not have "--save_dir" argument

### ISSUE THREAD

**Issue by WZG3661** [uber-research/DeepPruner#5]
I want to give two pictures, one is the left and the other is right, to predict the depth, so how should I run your code? Should I run finetune_kitti.py? I don't understand your Readme.txt, is finetune_kitti.py to train and test a model? I have  downloaded the pre-trained model and I just want to use it not to train it, should I run another .py docunment?  Really hope you can help me.

**Comment by ShivamDuggal4** [comment]
Hi @WZG3661 
There was a typo in deeppruner readme under the evaluation command section. I have fixed it now.
Just follow this command to run DeepPruner on any dataset.
https://github.com/uber-research/DeepPruner/tree/master/deeppruner#evaluation-command-on-any-dataset

Let me know for any other issue.

**Comment by WZG3661** [comment]
> Hi @WZG3661
> There was a typo in deeppruner readme under the evaluation command section. I have fixed it now.
> Just follow this command to run DeepPruner on any dataset.
> https://github.com/uber-research/DeepPruner/tree/master/deeppruner#evaluation-command-on-any-dataset
> 
> Let me know for any other issue.

Thanks a lot! 
But when I run the submission_kitti.py, I got another problem:
`File "/home/lihua/Downloads/StereoMatching/DeepPruner-master/deeppruner/submission_kitti.py", line 106, in main
    imgL = processed(imgL).numpy()
  
File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 49, in __call__
     img = t(img)

File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/transforms.py", line 76, in __call__
    return F.to_tensor(pic)

File "/usr/local/lib/python3.6/dist-packages/torchvision/transforms/functional.py", line 48, in to_tensor
    img = torch.from_numpy(pic.transpose((2, 0, 1)))

ValueError: axes don't match array`
My Pytorch version is 0.4.1, and my torchview version is 0.2.1, can you help me fix it?

**Comment by WZG3661** [comment]
I find that if I give two gray images, the problem above will arise. So I give two color images, but another problem arised:
tuple indices must be integers or slices, not tuple
in the line 128 of submissiong_kitti.py.

**Comment by ShivamDuggal4** [comment]
Hi @WZG3661 , it seems like your config file hasn't been set correctly for evaluation.
https://github.com/uber-research/DeepPruner/blob/b13a254773843b92ee8bbfb5dbc18cf9a3078ea4/deeppruner/models/config.py#L31

Please change the "mode" to "evaluation" in order to successfully run submission_kitti.py

**Comment by WZG3661** [comment]
Thaks a lot! Hope you can make it clear in Readme.txt.
