### ISSUE TITLE
weight_init

### ISSUE THREAD

**Issue by zyl1336110861** [uber-research/DeepPruner#6]
Hi! Thanks so much for your code! When I saw the code, I found the weight_init in SubModule you defined was not used. Do I understand correctly? Is there any problem if the init method you defined is not used?

**Comment by ShivamDuggal4** [comment]
Hi @zyl1336110861 Thanks for your interest in the code.

The weight_init defined in class SubModule is called for all classes defined in "models/submodules2d.py" and "models/submodules3d.py".

For the few convolution layers defined in "models/deeppruner.py" , I had mistakenly erased the call to  weight_init() during code cleaning. It was there during initial training for the paper results. I have corrected this typo now.

Secondly, I don't think that not using weight_init would have any major impact during training as pytorch default initializer would be called in that case and it generally works well too.
